Update .gitignore
faberordonez1/paginaWeb pull request #3
Opened 2020-11-26 04:26 UTC by faberordonez1

# Template Pull request

## Descripcion
¿Qué ha cambiado?

Agregamos al gitignore soporte para Nodej.s

- [ ] Frontend
- [ ] Backend
- [x] Configuracion del Server

## ¿Como puedo probar los cambios?

Por ejemplo los archivos y la carpeta node_modules ya no se suben al repo, ver el archivo .gitignore completo

2020-11-27 03:58 UTC, faberordonez commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/node
Unico cambio

2020-11-27 04:02 UTC, faberordonez commented
El cambio es el mismo

2020-11-27 04:03 UTC, faberordonez1 commented
Es el mismo se mejoro la descripción

2020-11-27 04:06 UTC, faberordonez requested changes
Pendiente adición ultima palabra

2020-11-29 18:36 UTC, faberordonez1 reviewed
Cambio realizado

2020-11-29 18:36 UTC, faberordonez1 commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/node
Se añadió la palabra

2020-11-29 19:23 UTC, faberordonez requested changes
agrega la palabra new

2020-11-29 19:25 UTC, faberordonez1 reviewed
agregada la palabra new

2020-11-29 19:32 UTC, faberordonez approved these changes

2020-11-29 19:32 UTC, merged